import java.awt.Color;
public class MenuFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form MenuPanel
     */
    public MenuFrame() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        aP1 = new javax.swing.JLabel();
        sP1 = new javax.swing.JLabel();
        fP1 = new javax.swing.JLabel();
        attemptsLabelP1 = new javax.swing.JLabel();
        successLabelP1 = new javax.swing.JLabel();
        failuresLabelP1 = new javax.swing.JLabel();
        aP2 = new javax.swing.JLabel();
        sP2 = new javax.swing.JLabel();
        fP2 = new javax.swing.JLabel();
        attemptsLabelP2 = new javax.swing.JLabel();
        successLabelP2 = new javax.swing.JLabel();
        failuresLabelP2 = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        ActiveP1 = new javax.swing.JLabel();
        ActiveP2 = new javax.swing.JLabel();
        Player2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        requestFocus(false);

        aP1.setText("Number of attempts:");

        sP1.setText("Number of success:");

        fP1.setText("Number of failures:");

        attemptsLabelP1.setText("     ");
        attemptsLabelP1.setName(""); // NOI18N

        attemptsLabelP2.setText("     ");
        attemptsLabelP2.setName(""); // NOI18N

        ActiveP1.setText(" ");

        jButton1.setText("Menu");

        jButton2.setText("Help");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fP2)
                                    .addComponent(sP2)
                                    .addComponent(aP2)
                                    .addComponent(fP1)
                                    .addComponent(sP1)
                                    .addComponent(aP1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attemptsLabelP2)
                                    .addComponent(successLabelP2)
                                    .addComponent(failuresLabelP2)
                                    .addComponent(failuresLabelP1)
                                    .addComponent(successLabelP1)
                                    .addComponent(attemptsLabelP1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Player1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ActiveP1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Player2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ActiveP2)))
                        .addGap(30, 30, 30)))
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {attemptsLabelP1, failuresLabelP1, successLabelP1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1)
                    .addComponent(ActiveP1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aP1)
                    .addComponent(attemptsLabelP1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sP1)
                    .addComponent(successLabelP1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fP1)
                    .addComponent(failuresLabelP1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player2)
                    .addComponent(ActiveP2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aP2)
                    .addComponent(attemptsLabelP2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sP2)
                    .addComponent(successLabelP2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fP2)
                    .addComponent(failuresLabelP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new MenuFrame().setVisible(true);
            }
        });
    }
    
    static public void updateMenuPanel()
    {
        attemptsLabelP1.setText(""+ SetOfCards.numberOfTries[1]);
        successLabelP1.setText(""+ SetOfCards.numberOfSuccess[1]);
        failuresLabelP1.setText(""+ SetOfCards.numberOfFailures[1]);
        
        if(SetOfCards.twoPlayers==true)
        {
        aP2.setText("Number of attempts:");
        sP2.setText("Number of success:");
        fP2.setText("Number of failures:");
        Player1.setText("Player 1");
        Player2.setText("Player 2");
        if(SetOfCards.player==1)
        {
            ActiveP1.setText("Active");
            ActiveP2.setText("");
        }
        else {
            ActiveP1.setText("");
            ActiveP2.setText("Active");
        }
        attemptsLabelP2.setText(""+ SetOfCards.numberOfTries[2]);
        successLabelP2.setText(""+ SetOfCards.numberOfSuccess[2]);
        failuresLabelP2.setText(""+ SetOfCards.numberOfFailures[2]);
        }
        
    }

    // Variables declaration - do not modify                     
    static private javax.swing.JLabel ActiveP1;
    static private javax.swing.JLabel ActiveP2;
    static private javax.swing.JLabel Player1;
    static private javax.swing.JLabel Player2;
    static private javax.swing.JLabel aP1;
    static private javax.swing.JLabel aP2;
    static private javax.swing.JLabel attemptsLabelP1;
    static private javax.swing.JLabel attemptsLabelP2;
    static private javax.swing.JLabel fP1;
    static private javax.swing.JLabel fP2;
    static private javax.swing.JLabel failuresLabelP1;
    static private javax.swing.JLabel failuresLabelP2;
    static private javax.swing.JButton jButton1;
    static private javax.swing.JButton jButton2;
    static private javax.swing.JLabel sP1;
    static private javax.swing.JLabel sP2;
    static private javax.swing.JLabel successLabelP1;
    static private javax.swing.JLabel successLabelP2;
    // End of variables declaration                   
}

